### ISSUE TITLE
Add .then and .catch to every promise made in Melonian

### ISSUE THREAD

**Issue by TheRandomMelon** [Melonz/Melonian#1]
Not doing so is deprecated, and eventually will crash Melonian if we don't do so.

**Comment by TheRandomMelon** [comment]
Commit 8ffb232682a74fe44d80d0011475ab8beb9aa403 is getting closer to what we want!

**Comment by mrdnomaid** [comment]
lol hash doesn't bother with any of this, who cares if it crashes

**Comment by TheRandomMelon** [comment]
like we do @mrdnomaid

**Comment by TheRandomMelon** [comment]
ehhhhh
