### ISSUE TITLE
Port Melonian to Discord.js

### ISSUE THREAD

**Issue by TheRandomMelon** [Melonz/Melonian#3]
"Discord.js is like C#, Eris is like Visual Basic."
\- @Technach

**Comment by Technach** [comment]
"0.0.2"
"milestone"

**Comment by TheRandomMelon** [comment]
yeah

**Comment by TheRandomMelon** [comment]
Starting development of this. hopefully it'll be done sometime this year ffs

**Comment by TheRandomMelon** [comment]
# For those seeking information on Melonian's rewrite
Melonian's rewrite will bring to the table: (checkmark = done)

[ ] A custom command client by @Technach, for more flexibility
[ ] A MySQL database system, so that it's easier to manage (no more JSON files!)
[ ] A real strike and merit system (thanks MySQL!)
...and probably more! 

Stay tuned.

**Comment by SunburntRock89** [comment]
assigned me

**Comment by TheRandomMelon** [comment]
uh-huh. we need to finish development of this lol

**Comment by SunburntRock89** [comment]
I thought you were using sql

**Comment by TheRandomMelon** [comment]
well @Technach doesn't seem to be doing shit

**Comment by SunburntRock89** [comment]
ok...
I kinda have a lot on my hands lol, ive got like, another bot that practically does the same thing.,

**Comment by TheRandomMelon** [comment]
that's the whole point of this development stage. get an actual decent base so we can make it a tad more "jack-of-all-trades", like for instance, add a starboard feature?

**Comment by SunburntRock89** [comment]
yeah, again, the bot im working on does exactly that

**Comment by TheRandomMelon** [comment]
What bot?

**Comment by SunburntRock89** [comment]
there's no name for it atm, and its a private repo

**Comment by SunburntRock89** [comment]
but its a lot more developed than melonian

**Comment by TheRandomMelon** [comment]
...and that's a problem. i need to get my ass moving then

**Comment by SunburntRock89** [comment]
if its shit I am going to kill you

**Comment by TheRandomMelon** [comment]
define "shit"

**Comment by SunburntRock89** [comment]
Bad code, not linted, not using async await synthax, "function" etc

**Comment by SunburntRock89** [comment]
do you know what I mean by function

**Comment by TheRandomMelon** [comment]
yes,
```js
arr.forEach(function () {

});
```

**Comment by SunburntRock89** [comment]
yes, disgusting

**Comment by SunburntRock89** [comment]
there's no point in using the function function

**Comment by SunburntRock89** [comment]
![The other bot's code](https://letsencrypt.works.wtf/holy/shit/it/does/c0b8b.png)

**Comment by TheRandomMelon** [comment]
Error Fetching Resource

**Comment by SunburntRock89** [comment]
Seriously

**Comment by TheRandomMelon** [comment]
![image](https://user-images.githubusercontent.com/22629722/37566245-8456cb8e-2a84-11e8-96e9-39dd2e2a3c4c.png)
mhm

**Comment by SunburntRock89** [comment]
![try again?](http://letsencrypt.works.wtf/holy/shit/it/does/c0b8b.png)

**Comment by SunburntRock89** [comment]
kill me

**Comment by TheRandomMelon** [comment]
same thing (just DM me)(

**Comment by SunburntRock89** [comment]
http://letsencrypt.works.wtf/holy/shit/it/does/c0b8b.png

**Comment by TheRandomMelon** [comment]
I see

**Comment by TheRandomMelon** [comment]
![image](https://user-images.githubusercontent.com/22629722/37566253-a43069d8-2a84-11e8-887d-4c9ed2300bfc.png)
while this is all we have...

**Comment by SunburntRock89** [comment]
mine's is functional 😉

**Comment by TheRandomMelon** [comment]
:(

**Comment by SunburntRock89** [comment]
By that I mean most moderation commands are working, modlogging infastructure is there, but semi borked and that's it.

**Comment by TheRandomMelon** [comment]
cool

**Comment by oskikiboy** [comment]
ooh this seems fun, ima join the development sizzle

**Comment by oskikiboy** [comment]
~~How about multithreading~~

**Comment by SunburntRock89** [comment]
sharding*

**Comment by SunburntRock89** [comment]
Why bother multithreading without sharding

**Comment by oskikiboy** [comment]
nein

**Comment by oskikiboy** [comment]
Multithreading that uses sharding so that shit doesn't fuck up

**Comment by oskikiboy** [comment]
But the main idea behind it is multithreading

**Comment by oskikiboy** [comment]
I'm locked out of discord rn 😂

**Comment by oskikiboy** [comment]
What happened to Object orientated programming :(

**Comment by oskikiboy** [comment]
Klasa is a thing too.....

**Comment by aleksanderxh** [comment]
I think sharding and/or multithreading is kinda overkill for Melonian. It's a small (but good) bot, and it 
wouldn't be efficient to do it as it's unnecessary. If we need it, we should do the base and core commands first, the work on this. When this becomes a bigger project, then this would be useful, however, right now... it's better to be left alone.

**Comment by SunburntRock89** [comment]
>But good
>when it becomes bigger

**Comment by TheRandomMelon** [comment]
I love your enthusiasm @SunburntRock89, really motivating

**Comment by KingDGrizzle** [comment]
Do you people not have Discord?

**Comment by oskikiboy** [comment]
na

**Comment by TheRandomMelon** [comment]
Well I mean, we need just one place to chat. Not everyone's on the Melonz Discord.

BTW,

<a href="https://discord.gg/rQBPWrV

**Comment by TheRandomMelon** [comment]
Closed on GitLab, so might as well close it here
